/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdmradar_gui.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(aa14d49ea7415ddc7d28aa28a5911697)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <QWidget>

namespace py = pybind11;

#include <ofdmradar/ofdmradar_gui.h>
// pydoc.h is automatically generated in the build directory
#include <ofdmradar_gui_pydoc.h>

void bind_ofdmradar_gui(py::module &m)
{
    using ofdmradar_gui = gr::ofdmradar::ofdmradar_gui;

    py::class_<ofdmradar_gui, gr::block, gr::basic_block, std::shared_ptr<ofdmradar_gui>>(
        m, "ofdmradar_gui", D(ofdmradar_gui))

        .def(py::init(&ofdmradar_gui::make),
             py::arg("ofdm_params"),
             py::arg("parent") = nullptr,
             D(ofdmradar_gui, make))

        .def("pyqwidget", &ofdmradar_gui::pyqwidget);
}
